export const brand = {
  name: "Momoka",
  productName: "Momoka POS",
  onlineName: "Momoka Online",
  storePhone: "0966108435",
  storePhoneDisplay: "0966 108 435",
  storeZaloUrl: "https://zalo.me/0966108435",
  storeHours: "09:00 - 22:00",
  address: "Chi Long, Yên Phong, Bắc Ninh",
  orderingUrl: "moka.claro.vn",
  categoriesTagline: "Kem - Trà sữa - Cafe - Mì cay",
  authName: "Momoka Auth",
  kitchenName: "Momoka Kitchen",
  reportsName: "Momoka Reports",
  adminName: "Momoka Admin",
  inventoryName: "Kho nguyên liệu Momoka",
  orderHistoryName: "Lịch sử đơn Momoka",
  tagline: "Bán nhanh, bếp rõ, báo cáo tức thì.",
  operatorLine: "Hệ thống vận hành cửa hàng và quản lý đơn hàng theo thời gian thực.",
  authLine: "Đăng nhập để vận hành cửa hàng Momoka trên cùng một giao diện thống nhất.",
  kitchenLine: "Theo dõi nhịp bếp, tiến độ và ưu tiên món trong nhịp bán liên tục.",
  reportsLine: "Đọc doanh thu, nhìn xu hướng và bóc tách dữ liệu trong một màn hình.",
  inventoryLine: "Kiểm soát nguyên liệu, công thức và cảnh báo tồn kho sắp chạm ngưỡng.",
  adminLine: "Quản lý menu, danh mục và tuỳ chọn bán hàng theo chuẩn thương hiệu Momoka.",
  historyLine: "Tra cứu toàn bộ đơn hàng, in lại chứng từ và đối chiếu vận hành.",
  // Cấu hình ngân hàng để nhận chuyển khoản (Sử dụng cho VietQR)
  bankName: "VietinBank",
  bankCode: "970415",
  bankId: "ICB", 
  bankAccount: "100868631089", 
  bankAccountName: "NGUYEN VAN TU",
} as const;
